import { IEmployee, ICompany } from './types';
import photo_01 from '../images/photo_01.png';
import photo_02 from '../images/photo_02.png';
import photo_03 from '../images/photo_03.png';
import logo from '../images/Logo.png';

export const employee: IEmployee = {
  id: 1,
  name: 'Иванов\nИван Петрович ',
  position: 'Директор',
  photos: [photo_01, photo_02, photo_03],
  mobilePhoneNumber: '+7 (000) 123-45-67',
  phoneNumbers: ['+7 (812) 212-85-06', '+7 (000) 000-00-00'],
  email: 'director@mail.ru',
  privateSite: 'http://director.company.ru',
  address: 'Адрес директора',
  birthDate: new Date('1955-12-02'),
  rank: 'Звание, учёная степень',
  companyId: 1,
  socialLinks: [
    { name: 'Telegram', url: 'https://t.me/director' },
    { name: 'Whatsapp', url: 'https://wa.me/78122128506' },
    { name: 'Viber', url: 'viber://chat?number=78122128506' },
    { name: 'Instagram', url: 'https://www.instagram.com/director' },
    { name: 'VK', url: 'https://vk.com/director' },
    { name: 'Facebook', url: 'https://www.facebook.com/director' },
    { name: 'Youtube', url: 'https://www.youtube.com/channel/director' },
    { name: 'OK', url: 'https://ok.ru/director' },
    { name: 'Dzen', url: 'https://dzen.ru/director' },
    { name: 'TikTok', url: 'https://www.tiktok.com/@director' },
    { name: 'LinkedIn', url: 'https://www.linkedin.com/in/director' },
    { name: 'ICQ', url: 'https://icq.im/director' },
    { name: 'Twitter', url: 'https://x.com/director' },
    { name: 'Skype', url: 'skype:director?chat' },
    { name: 'TenChat', url: 'https://tenchat.com/director' },
  ],
};

export const company: ICompany = {
  id: 1,
  name: 'Название компании',
  description: 'Обеспечивать клиентов высококачественными материалами по доступным ценам, способствуя развитию любой отрасли в России.',
  logoImage: logo,
  phoneNumber: '+7 (000) 000-00-00',
  address: 'Адрес компании',
  email: 'company@mail.ru',
  privateSite: 'http://company.ru',
  foundedDate: new Date('2000-01-01'),
  fax: '+7 (000) 000-00-00',
  clients: [
    'Клиент 1',
    'Клиент 2',
    'Клиент 3',
    'Клиент 4',
    'Клиент 5',
    'Клиент 6',
    'Клиент 7',
    'Клиент 8',
    'Клиент 9',
    'Клиент 10',
  ],
  socialLinks: [
    { name: 'telegram', url: 'https://t.me/company' },
    { name: 'whatsapp', url: 'https://wa.me/70000000000' },
    { name: 'viber', url: 'viber://chat?number=+70000000000' },
    { name: 'instagram', url: 'https://www.instagram.com/company' },
    { name: 'vk', url: 'https://vk.com/company' },
    { name: 'facebook', url: 'https://www.facebook.com/company' },
    { name: 'youtube', url: 'https://www.youtube.com/channel/company' },
    { name: 'ok', url: 'https://ok.ru/company' },
    { name: 'dzen', url: 'https://dzen.ru/company' },
    { name: 'tikTok', url: 'https://www.tiktok.com/@company' },
    { name: 'linkedin', url: 'https://www.linkedin.com/company/company' },
    { name: 'icq', url: 'https://icq.im/company' },
    { name: 'twitter', url: 'https://x.com/company' },
    { name: 'skype', url: 'skype:company?chat' },
    { name: 'tenchat', url: 'https://tenchat.com/company' },
  ],
};
